use_frameworks!

target 'RxJTAppleCalendar_Example' do
  pod 'RxJTAppleCalendar', :path => '../'

  target 'RxJTAppleCalendar_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
